<a href="https://colab.research.google.com/github/fadlifernando10/pm-turi2-preprocessing-FadliFernando/blob/main/PM_P4_FadliFernando_2488010043.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
import numpy as np

data = {
    'usia'      : [25, 32, np.nan, 45, 28, 51, 38, np.nan, 29, 41],
    'pendapatan': [4_000_000, 7_500_000, 5_200_000, 12_000_000, 4_800_000,
                   15_000_000, 8_100_000, 6_300_000, np.nan, 9_900_000],
    'pendidikan': ['SMA','S1','SMA','S2','SMA','S2','S1','S1','SMA','S2'],
    'kota'      : ['Bandung','Jakarta','Bandung','Surabaya','Jakarta',
                   'Surabaya','Jakarta','Bandung','Bandung','Jakarta'],
    'divisi'    : ['IT', 'HR', 'IT', 'Finance', 'HR', 'Finance', 'IT', 'HR', 'Finance', 'IT'],
    'membeli'   : ['Tidak','Ya','Tidak','Ya','Tidak','Ya','Ya','Tidak','Tidak','Ya']
}
df = pd.DataFrame(data)
df

   usia  pendapatan pendidikan      kota   divisi membeli
0  25.0   4000000.0        SMA   Bandung       IT   Tidak
1  32.0   7500000.0         S1   Jakarta       HR      Ya
2   NaN   5200000.0        SMA   Bandung       IT   Tidak
3  45.0  12000000.0         S2  Surabaya  Finance      Ya
4  28.0   4800000.0        SMA   Jakarta       HR   Tidak
5  51.0  15000000.0         S2  Surabaya  Finance      Ya
6  38.0   8100000.0         S1   Jakarta       IT      Ya
7   NaN   6300000.0         S1   Bandung       HR   Tidak
8  29.0         NaN        SMA   Bandung  Finance   Tidak
9  41.0   9900000.0         S2   Jakarta       IT      Ya

In [24]:
df['usia'] = df['usia'].fillna(df['usia'].mean())
df['pendapatan'] = df['pendapatan'].fillna(df['pendapatan'].mean())

In [25]:
X = df.drop(columns=['membeli'])
y = df['membeli']

In [26]:
X['pendidikan'] = X['pendidikan'].map({'SMA': 0, 'S1': 1, 'S2': 2})
X = pd.get_dummies(X, columns=['kota', 'divisi'], dtype=int)
y = y.map({'Tidak': 0, 'Ya': 1})

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [27]:
from sklearn.preprocessing import MinMaxScaler

num = ['usia', 'pendapatan', 'pendidikan']
sc = MinMaxScaler()

X_train[num] = sc.fit_transform(X_train[num])
display(X_train.describe())

,usia,pendapatan,pendidikan,kota_Bandung,kota_Jakarta,kota_Surabaya
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,0.514286,0.398214,0.428571,0.428571,0.428571,0.142857
std,0.349660,0.367808,0.449868,0.534522,0.534522,0.377964
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.325000,0.125000,0.000000,0.000000,0.000000,0.000000
50%,0.500000,0.287500,0.500000,0.000000,0.000000,0.000000
75%,0.725000,0.625000,0.750000,1.000000,1.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [28]:
print("Jumlah missing value:", X_train.isnull().sum().sum())
display(X_train.head())

Jumlah missing value: 0

   usia  pendapatan  pendidikan  kota_Bandung  kota_Jakarta  kota_Surabaya
0  0.00      0.0000         0.0             1             0              0
7  0.50      0.2875         0.5             1             0              0
2  0.50      0.1500         0.0             1             0              0
9  0.80      0.7375         1.0             0             1              0
4  0.15      0.1000         0.0             0             1              0

E. Refleksi
1. Mengapa urutan 'split dulu, baru scaling' prnting?

Untuk mencegah terjadinya kebocoran data, dimana informasi dari data uji ikut terhitung saat mencari nilai rata rata.

2. Kapan label encoding dan kapan one-hot encoding?

label encoding: digunakan jika data kategori memiliki tingkatan atau urutan yang jelas. contohnya: sma - s1 - s2

one-hot encodingdigunakan jika data kategori nominal yang tidak punya tingkatan. contoh: nama kota seperti bandung, jakarta, surabaya agar komputer tidak salah menganggap angka kategorinya memiliki urutan nilai

3. Apa perbedaan normalisasi dan standarisasi?

normalisasi seperti MinMaxScaler mengubah skala data ke rentang tertentu(0 sampai 1) sedangkan standarisasi seperti StandardScaler mengubah data agar memiliki rata rata (mean) sama dengan 0 dan standar deviasi sama dengan 1